cp dot-Xresources $HOME/.Xresources
cp dot-ctwmrc $HOME/.ctwmrc
cp dot-gitconfig $HOME/.gitconfig
cp dot-setdual.sh $HOME/.setdual.sh
cp dot-tcshrc $HOME/.tcshrc
cp dot-vimrc $HOME/.vimrc
cp dot-xinitrc $HOME/.xinitrc
cp dot-xprofile $HOME/.xprofile
ln $HOME/.xinitrc $HOME/.xsession
