#!/bin/sh
#set -x

cleanup() {
	echo "cleaning up"
	killall ssh-agent-card-prompt dbus-daemon redshift picom
	rm -f ~/.Xauthority
	rm -rf ~/.local/share/Trash
}
trap cleanup INT TERM QUIT

xrdb -merge /home/rgeorgia/.Xresources

export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export MOZ_ACCELERATED=1
export MOZ_WEBRENDER=1

# to allow style changes with qt5ct
export QT_QPA_PLATFORMTHEME="qt5ct"

xsetroot -cursor_name left_ptr
xmodmap ~/.xmodmap
xset b 0 0 0
xset r rate 350 35

# disable built-in saver, because xidle will handle it
xset s off
# disable dpms, because slock will handle it
xset dpms 0 0 0

## test for an existing bus daemon, just to be safe
if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
## if not found, launch a new one
	eval `dbus-launch --sh-syntax`
	echo "D-Bus per-session daemon address is: $DBUS_SESSION_BUS_ADDRESS"
fi

redshift -l 41.90:-87.66 -t 5000:3500 -m randr &

/usr/pkg/bin/openbox-session
# startxfce4
# /usr/X11R7/bin/ctwm

cleanup
